import { icons } from "./icons";

export const tabs: AppTab[] = [
    { name: "index", title: "Home", icon: icons.home },
    { name: "subscriptions", title: "Subscriptions", icon: icons.wallet },
    { name: "insights", title: "Insights", icon: icons.activity },
    { name: "settings", title: "Settings", icon: icons.setting },
];

export const HOME_USER = {
    name: "Sagar Maharjan | Fullstack Developer",
};

export const HOME_BALANCE = {
    amount: 2489.48,
    nextRenewalDate: "2026-03-18T09:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
    {
        id: "spotify",
        icon: icons.spotify,
        name: "Spotify",
        price: 5.99,
        currency: "USD",
        daysLeft: 2,
    },
    {
        id: "notion",
        icon: icons.notion,
        name: "Notion",
        price: 12.0,
        currency: "USD",
        daysLeft: 4,
    },
    {
        id: "figma",
        icon: icons.figma,
        name: "Figma",
        price: 15.0,
        currency: "USD",
        daysLeft: 6,
    },
];

export const HOME_SUBSCRIPTIONS: Subscription[] = [
    {
        id: "adobe-creative-cloud",
        icon: icons.adobe,
        name: "Adobe Creative Cloud",
        plan: "Teams Plan",
        category: "Design",
        paymentMethod: "Visa ending in 8530",
        status: "active",
        startDate: "2025-03-20T10:00:00.000Z",
        price: 77.49,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-20T10:00:00.000Z",
        color: "#f5c542",
    },
    {
        id: "github-pro",
        icon: icons.github,
        name: "GitHub Pro",
        plan: "Developer",
        category: "Developer Tools",
        paymentMethod: "Mastercard ending in 2408",
        status: "active",
        startDate: "2024-11-24T10:00:00.000Z",
        price: 9.99,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-24T10:00:00.000Z",
        color: "#e8def8",
    },
    {
        id: "claude-pro",
        icon: icons.claude,
        name: "Claude Pro",
        plan: "Pro Plan",
        category: "AI Tools",
        paymentMethod: "Amex ending in 1010",
        status: "paused",
        startDate: "2025-06-27T10:00:00.000Z",
        price: 20.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-27T10:00:00.000Z",
        color: "#b8d4e3",
    },
    {
        id: "canva-pro",
        icon: icons.canva,
        name: "Canva Pro",
        plan: "Yearly Access",
        category: "Design",
        paymentMethod: "Visa ending in 7784",
        status: "cancelled",
        startDate: "2024-04-02T10:00:00.000Z",
        price: 119.99,
        currency: "USD",
        billing: "Yearly",
        renewalDate: "2026-04-02T10:00:00.000Z",
        color: "#b8e8d0",
    },
];

export const ALL_SUBSCRIPTIONS: Subscription[] = [
    ...HOME_SUBSCRIPTIONS,
    {
        id: "spotify-premium",
        icon: icons.spotify,
        name: "Spotify Premium",
        plan: "Individual",
        category: "Entertainment",
        paymentMethod: "Apple Pay",
        status: "active",
        startDate: "2023-01-15T10:00:00.000Z",
        price: 10.99,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-22T10:00:00.000Z",
        color: "#b8f0d8",
    },
    {
        id: "notion-plus",
        icon: icons.notion,
        name: "Notion Plus",
        plan: "Plus Plan",
        category: "Productivity",
        paymentMethod: "Visa ending in 4242",
        status: "active",
        startDate: "2024-02-10T10:00:00.000Z",
        price: 12.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-25T10:00:00.000Z",
        color: "#f7e8d0",
    },
    {
        id: "figma-professional",
        icon: icons.figma,
        name: "Figma Professional",
        plan: "Professional",
        category: "Design",
        paymentMethod: "Mastercard ending in 9012",
        status: "active",
        startDate: "2024-08-01T10:00:00.000Z",
        price: 15.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-28T10:00:00.000Z",
        color: "#ffd8cc",
    },
    {
        id: "chatgpt-plus",
        icon: icons.openai,
        name: "ChatGPT Plus",
        plan: "Plus Plan",
        category: "AI Tools",
        paymentMethod: "Visa ending in 8530",
        status: "active",
        startDate: "2023-11-06T10:00:00.000Z",
        price: 20.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-04-06T10:00:00.000Z",
        color: "#cbf2e2",
    },
    {
        id: "dropbox-plus",
        icon: icons.dropbox,
        name: "Dropbox Plus",
        plan: "Plus 2TB",
        category: "Cloud Storage",
        paymentMethod: "PayPal ending in 3311",
        status: "paused",
        startDate: "2023-05-18T10:00:00.000Z",
        price: 11.99,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-04-18T10:00:00.000Z",
        color: "#d2e5fa",
    },
    {
        id: "medium-membership",
        icon: icons.medium,
        name: "Medium Membership",
        plan: "Member",
        category: "Reading",
        paymentMethod: "Apple Pay",
        status: "active",
        startDate: "2024-09-12T10:00:00.000Z",
        price: 5.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-04-12T10:00:00.000Z",
        color: "#eaecee",
    },
];